apiVersion: v1
kind: ConfigMap
metadata:
  name: inferenceservice-config
  namespace: set
data:
  metricsAggregator: |-
    {
      "enableMetricAggregation": "false",
      "enablePrometheusScraping" : "false"
    }
